# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='university',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='common_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='average_age',
        ),
        migrations.RemoveField(
            model_name='program',
            name='faculty',
        ),
        migrations.AddField(
            model_name='program',
            name='cost_per_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='custom_exam',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='form',
            field=models.CharField(choices=[('fulltime', 'Очная'), ('distance', 'Дистанционная'), ('extramural', 'Заочная'), ('mixed', 'Очно-заочная'), ('night', 'Вечерняя')], default='fulltime', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(default='bachelor', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='places',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='ucheba_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.University'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='region_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('gov', 'Государственный'), ('mun', 'Муниципальный'), ('ind', 'Частный')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requiredexam',
            name='exam',
            field=models.CharField(choices=[('soc', 'Обществознание'), ('geo', 'География'), ('lit', 'Литература'), ('phy', 'Физика'), ('his', 'История'), ('for', 'Иностранный язык'), ('ict', 'Информатика и ИКТ'), ('rus', 'Русский язык'), ('mat', 'Математика'), ('che', 'Химия'), ('bio', 'Биология')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
