# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20171009_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='graduate_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='ucheba_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
