# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20171009_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='first_passing_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='form',
            field=models.CharField(choices=[('fulltime', 'очная'), ('distance', 'дистанционная'), ('extramural', 'заочная'), ('mixed', 'очно-заочная'), ('night', 'вечерняя')], max_length=64),
        ),
    ]
