# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20171009_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='average_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='employment_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
