# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_auto_20171009_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='custom_exam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
