# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_auto_20171009_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='cost_per_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
