# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_auto_20171009_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredexam',
            name='exam',
            field=models.CharField(choices=[('soc', 'Обществознание'), ('geo', 'География'), ('lit', 'Литература'), ('phy', 'Физика'), ('his', 'История'), ('lan', 'Иностранный язык'), ('ict', 'Информатика и ИКТ'), ('rus', 'Русский язык'), ('mat', 'Математика'), ('che', 'Химия'), ('bio', 'Биология')], max_length=3),
        ),
    ]
