# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_auto_20171011_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
