# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0011_auto_20171013_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
