# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0012_program_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='continued_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
